/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Number format
 */
export type AgentI18nContextDataNumberFormat = {[key: string]: string};
