/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { AgentI18nContextDataNumberFormat } from './agentI18nContextDataNumberFormat';
import type { AgentI18nContextDataUserId } from './agentI18nContextDataUserId';
import type { AgentI18nContextDataSessionId } from './agentI18nContextDataSessionId';

/**
 * Agent i18n context data for inter-agent communication.
 */
export interface AgentI18nContextData {
  /** Language */
  language: string;
  /** Timezone */
  timezone: string;
  /** Currency symbol */
  currency_symbol: string;
  /** Date format */
  date_format: string;
  /** Time format */
  time_format: string;
  /** Number format */
  number_format: AgentI18nContextDataNumberFormat;
  /** User ID */
  user_id?: AgentI18nContextDataUserId;
  /** Session ID */
  session_id?: AgentI18nContextDataSessionId;
}
