/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Currency formatting result data.
 */
export interface CurrencyFormatData {
  /** Original amount */
  original: number;
  /** Formatted amount */
  formatted: string;
  /** Number of decimal places */
  decimal_places: number;
  /** Language */
  language: string;
  /** Currency symbol */
  currency_symbol: string;
}
