/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * DateTime formatting request.
 */
export interface DateTimeFormatRequest {
  /** ISO datetime string */
  datetime: string;
  /** Format type: date, time, or datetime */
  format_type?: string;
}
