/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * DateTime formatting result data.
 */
export interface DateTimeFormatData {
  /** Original datetime */
  original: string;
  /** Formatted datetime */
  formatted: string;
  /** Format type */
  format_type: string;
  /** Language */
  language: string;
  /** Timezone */
  timezone: string;
}
