/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { I18nConfigDataNumberFormat } from './i18nConfigDataNumberFormat';

/**
 * I18n configuration data model.
 */
export interface I18nConfigData {
  /** Current language */
  language: string;
  /** Current timezone */
  timezone: string;
  /** Date format */
  date_format: string;
  /** Time format */
  time_format: string;
  /** DateTime format */
  datetime_format: string;
  /** Currency symbol */
  currency_symbol: string;
  /** Number format */
  number_format: I18nConfigDataNumberFormat;
  /** Whether text is right-to-left */
  is_rtl: boolean;
}
