/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Language detection result data.
 */
export interface LanguageDetectionData {
  /** Detected language */
  detected_language: string;
  /** Language name */
  language_name: string;
  /** Whether the language is supported */
  is_supported: boolean;
}
