/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Number formatting result data.
 */
export interface NumberFormatData {
  /** Original number */
  original: number;
  /** Formatted number */
  formatted: string;
  /** Number of decimal places */
  decimal_places: number;
  /** Language */
  language: string;
}
