/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { SuccessResponseDateTimeFormatDataData } from './successResponseDateTimeFormatDataData';

export interface SuccessResponseDateTimeFormatData {
  /** Success status code */
  code?: number;
  /** Success message */
  msg?: string;
  /** Response data */
  data?: SuccessResponseDateTimeFormatDataData;
}
