/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { TimezonesData } from './timezonesData';

/**
 * Response data
 */
export type SuccessResponseTimezonesDataData = TimezonesData | null;
