/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { AgentI18nContextData } from './agentI18nContextData';

/**
 * Response data
 */
export type SuccessResponseAgentI18nContextDataData = AgentI18nContextData | null;
