/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Supported language schema.
 */
export interface SupportedLanguage {
  /** Language code */
  code: string;
  /** Language name */
  name: string;
  /** Whether this is the current language */
  is_current: boolean;
}
