/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { TimezoneInfo } from './timezoneInfo';

/**
 * Timezones data.
 */
export interface TimezonesData {
  /** List of timezones */
  timezones: TimezoneInfo[];
  /** Current timezone */
  current: string;
}
