/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */

/**
 * Timezone information schema.
 */
export interface TimezoneInfo {
  /** Timezone value */
  value: string;
  /** Timezone display name */
  label: string;
  /** Whether this is the current timezone */
  is_current: boolean;
}
