/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationDataVariables } from './translationDataVariables';

/**
 * Translation result data.
 */
export interface TranslationData {
  /** Translation key */
  key: string;
  /** Translated text */
  translated_text: string;
  /** Target language */
  language: string;
  /** Variables */
  variables?: TranslationDataVariables;
}
