/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationRequestLanguage } from './translationRequestLanguage';
import type { TranslationRequestVariables } from './translationRequestVariables';

/**
 * Translation request.
 */
export interface TranslationRequest {
  /** Translation key */
  key: string;
  /** Target language */
  language?: TranslationRequestLanguage;
  /** Variables for string formatting */
  variables?: TranslationRequestVariables;
}
