/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { UserI18nSettingsDataUserId } from './userI18nSettingsDataUserId';
import type { UserI18nSettingsDataCreatedAt } from './userI18nSettingsDataCreatedAt';
import type { UserI18nSettingsDataUpdatedAt } from './userI18nSettingsDataUpdatedAt';

/**
 * User i18n settings data.
 */
export interface UserI18nSettingsData {
  /** User ID */
  user_id?: UserI18nSettingsDataUserId;
  /** User language */
  language?: string;
  /** User timezone */
  timezone?: string;
  /** Creation timestamp */
  created_at?: UserI18nSettingsDataCreatedAt;
  /** Update timestamp */
  updated_at?: UserI18nSettingsDataUpdatedAt;
}
