/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ValueCell Server API
 * A community-driven, multi-agent platform for financial applications
 * OpenAPI spec version: 0.1.0
 */
import type { UserI18nSettingsRequestLanguage } from './userI18nSettingsRequestLanguage';
import type { UserI18nSettingsRequestTimezone } from './userI18nSettingsRequestTimezone';

/**
 * User i18n settings update request.
 */
export interface UserI18nSettingsRequest {
  /** Language to update */
  language?: UserI18nSettingsRequestLanguage;
  /** Timezone to update */
  timezone?: UserI18nSettingsRequestTimezone;
}
